FROM python:3.12
RUN pip install poetry

WORKDIR /srcs
COPY pyproject.toml poetry.lock ./
COPY srcs srcs
RUN poetry install --no-root

EXPOSE 8000

ARG DB_NAME
ARG LANGCHAIN_API_KEY
ARG LANGCHAIN_ENDPOINT
ARG LANGCHAIN_PROJECT
ARG LANGCHAIN_TRACING_V2
ARG MONGO_SRV
ARG OPENAI_API_KEY
ARG SENTRY_DSN

ENV DB_NAME=${DB_NAME} \
    LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY} \
    LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT} \
    LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT} \
    LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2} \
    MONGO_SRV=${MONGO_SRV} \
    OPENAI_API_KEY=${OPENAI_API_KEY} \
    SENTRY_DSN=${SENTRY_DSN}

WORKDIR /srcs/srcs
ENTRYPOINT ["poetry", "run", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
