name: Deploy to Amazon ECS

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      yes:
        description: 'yes'     
        required: true
        default: 'no'
      tags:
        description: 'manual deploy to ecs'  

env:
  AWS_REGION: ap-northeast-2                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: oatnote/ai           # set this to your Amazon ECR repository name
  ECS_SERVICE: oatnote-ai-stage-service                 # set this to your Amazon ECS service name
  ECS_CLUSTER: oatnote-stage-cluster                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: .aws/task-definition.json # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: oatnote-ai-stage-container           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions: write-all

jobs:
  deploy:
    name: Deploy
    if: ${{ github.actor == 'github-actions' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get the latest commit hash
      id: get_commit
      run: echo "LATEST_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ env.LATEST_COMMIT_HASH }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker buildx build \
          --build-arg FLOW="STAGE" \
          --build-arg DB_NAME_STAGE="${{ secrets.DB_NAME_STAGE }}" \
          --build-arg DB_NAME_PROD="${{ secrets.DB_NAME_PROD }}" \
          --build-arg LANGCHAIN_API_KEY="${{ secrets.LANGCHAIN_API_KEY }}" \
          --build-arg LANGCHAIN_ENDPOINT="${{ secrets.LANGCHAIN_ENDPOINT }}" \
          --build-arg LANGCHAIN_PROJECT="${{ secrets.LANGCHAIN_PROJECT }}" \
          --build-arg LANGCHAIN_TRACING_V2="${{ secrets.LANGCHAIN_TRACING_V2 }}" \
          --build-arg MONGO_SRV="${{ secrets.MONGO_SRV }}" \
          --build-arg OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
          --build-arg SENTRY_DSN="${{ secrets.SENTRY_DSN }}" \
          --build-arg VOYAGE_API_KEY="${{ secrets.VOYAGE_API_KEY }}" \
          -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
